(()=>{
'use strict';
if(window.__PFC_RESTORE_RUNNING__)return;window.__PFC_RESTORE_RUNNING__=true;
const EXPECTED='https://tama-fit.github.io',DB='TamaFitPhotoDB',STORE='BodyPhotos';
const F={dat:'tf_dat',tg:'tf_tg',fav:'tf_fav',favSettings:'tf_fav_settings',my:'tf_my',hist:'tf_hist',date:'tf_date',body:'tf_body'},num=v=>Number.isFinite(parseFloat(v))?parseFloat(v):0;
function photos(){return new Promise(resolve=>{let r;try{r=indexedDB.open(DB)}catch(_){resolve([]);return}let u=false;r.onupgradeneeded=e=>{u=true;try{e.target.transaction.abort()}catch(_){}};r.onerror=()=>resolve([]);r.onsuccess=e=>{const db=e.target.result;if(!db.objectStoreNames.contains(STORE)){db.close();resolve([]);return}const q=db.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>{const a=q.result||[];db.close();resolve(a)};q.onerror=()=>{db.close();resolve([])}}})}
async function backup(){const d={};for(const[k,v]of Object.entries(F))d[k]=localStorage.getItem(v);const raw={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('tf_'))raw[k]=localStorage.getItem(k)}const p=await photos();d._pfcRescue={format:'pfc-pre-restore-backup-v1',exportedAt:new Date().toISOString(),sourceOrigin:location.origin,rawPfcStorage:raw,bodyPhotos:p,bodyPhotoCount:p.length};return d}
async function save(d,n){const f=new File([JSON.stringify(d,null,2)],n,{type:'application/json'});try{if(navigator.canShare?.({files:[f]})&&navigator.share){await navigator.share({files:[f],title:'PFCバックアップ'});return}}catch(e){if(e?.name==='AbortError')return}const a=document.createElement('a');a.href=URL.createObjectURL(f);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function norm(d){const o={};if(d.dat){const a=JSON.parse(d.dat);o.dat=JSON.stringify(a.map(x=>({id:x.id||Date.now()+Math.floor(Math.random()*1000),N:x.N||x.n||'不明な食品',P:num(x.P??x.p),F:num(x.F??x.f),C:num(x.C??x.c),A:num(x.A??x.a),Cal:Math.round(num(x.Cal??x.cal)),U:x.U||x.u||'-',time:x.time||'朝'})))}if(d.hist){const a=JSON.parse(d.hist);o.hist=JSON.stringify(a.map(h=>({d:h.d||'不明な日',s:{P:num(h.s?.P??h.s?.p),F:num(h.s?.F??h.s?.f),C:num(h.s?.C??h.s?.c),A:num(h.s?.A??h.s?.a),Cal:Math.round(num(h.s?.Cal??h.s?.cal))},l:(h.l||[]).map(x=>({id:x.id||Date.now()+Math.floor(Math.random()*1000),N:x.N||x.n||'不明',P:num(x.P??x.p),F:num(x.F??x.f),C:num(x.C??x.c),A:num(x.A??x.a),Cal:Math.round(num(x.Cal??x.cal)),U:x.U||x.u||'-',time:x.time||'朝'}))})))}if(d.my){const a=JSON.parse(d.my);o.my=JSON.stringify(a.map((x,i)=>({N:x.N||x.n||'不明',P:num(x.P??x.p),F:num(x.F??x.f),C:num(x.C??x.c),A:num(x.A??x.a),Cal:Math.round(num(x.Cal??x.cal)),Fav:!!(x.Fav||x.favorite||x.isFavorite),favoriteOrder:Number.isFinite(Number(x.favoriteOrder))?Number(x.favoriteOrder):i,useCount:Number.isFinite(Number(x.useCount))?Number(x.useCount):0,lastUsedAt:Number.isFinite(Number(x.lastUsedAt))?Number(x.lastUsedAt):0,createdAt:Number.isFinite(Number(x.createdAt))?Number(x.createdAt):Date.now()+i})))}if(d.tg){const t=JSON.parse(d.tg);if(t.alcMode===undefined)t.alcMode=false;if(t.autoReset===undefined)t.autoReset=true;o.tg=JSON.stringify(t)}for(const k of['fav','favSettings','date','body'])if(typeof d[k]==='string')o[k]=d[k];return o}
function put(p){return new Promise((resolve,reject)=>{if(!p.length){resolve(0);return}const r=indexedDB.open(DB,1);r.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};r.onerror=()=>reject(r.error);r.onsuccess=e=>{const db=e.target.result,tx=db.transaction(STORE,'readwrite'),st=tx.objectStore(STORE),keys=st.getAllKeys();keys.onerror=()=>reject(keys.error);keys.onsuccess=()=>{const used=new Set((keys.result||[]).map(String));let n=0;p.forEach((v,i)=>{if(!v||typeof v.imageData!=='string')return;const rec={...v};let id=String(rec.id||rec.timestamp||Date.now()+i);if(used.has(id)){let j=1;while(used.has(`${id}-legacy-${j}`))j++;id=`${id}-legacy-${j}`}rec.id=id;used.add(id);st.put(rec);n++});tx.oncomplete=()=>{db.close();resolve(n)};tx.onerror=()=>{db.close();reject(tx.error)}}}})}
const ov=document.createElement('div');ov.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(8,24,16,.82);display:flex;align-items:center;justify-content:center;padding:16px;font-family:system-ui,-apple-system,sans-serif;color:#172820';
const c=document.createElement('div');c.style.cssText='width:min(540px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:20px;padding:20px';c.innerHTML='<div style="font-size:12px;font-weight:900;color:#187a51">PFC RESTORE</div><h2 style="margin:5px 0">救出JSONから復元</h2><p style="font-size:13px;color:#5f7168">救出JSONを選んでください。</p>';
const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.style.cssText='display:block;width:100%;padding:12px;border:1px solid #d9e8df;border-radius:12px;margin:12px 0';
const info=document.createElement('div');info.style.cssText='font-size:13px;line-height:1.6;padding:12px;background:#f1faf5;border-radius:12px;display:none';
const bk=document.createElement('button');bk.textContent='現在の新PFCデータを先にバックアップ';bk.style.cssText='width:100%;border:0;border-radius:13px;padding:13px;margin-top:10px;background:#e8f4ee;color:#187a51;font-weight:900;display:none';
const go=document.createElement('button');go.textContent='確認して復元実行';go.style.cssText='width:100%;border:0;border-radius:13px;padding:14px;margin-top:9px;background:#187a51;color:#fff;font-weight:900;display:none';
const close=document.createElement('button');close.textContent='閉じる';close.style.cssText='width:100%;border:0;border-radius:13px;padding:12px;margin-top:9px;background:#eef1ef;color:#405048;font-weight:800';const st=document.createElement('div');st.style.cssText='font-size:12px;color:#5f7168;margin-top:10px;min-height:18px';let d=null;
input.onchange=async()=>{try{d=JSON.parse(await input.files[0].text());const fs=Object.keys(F).filter(k=>typeof d[k]==='string'&&d[k]);const p=Array.isArray(d._pfcRescue?.bodyPhotos)?d._pfcRescue.bodyPhotos:[];if(!fs.length&&!p.length)throw new Error('PFCデータがありません');info.style.display='block';info.innerHTML=`主要PFC項目: <b>${fs.length}/8</b><br>体型写真: <b>${p.length}枚</b><br>救出元: <b>${String(d._pfcRescue?.sourceOrigin||'不明')}</b>`;bk.style.display=go.style.display='block';st.textContent='復元前バックアップを推奨します。'}catch(e){d=null;info.style.display='block';info.textContent='読み込みエラー: '+(e?.message||e);bk.style.display=go.style.display='none'}};
bk.onclick=async()=>{st.textContent='現在データをバックアップ中…';await save(await backup(),`PFC_before_restore_${new Date().toISOString().slice(0,10)}.json`);st.textContent='バックアップ操作を完了しました。'};
go.onclick=async()=>{if(!d)return;if(location.origin!==EXPECTED&&!confirm(`新PFC (${EXPECTED}) 上で実行する想定です。\n現在: ${location.origin}\n続けますか？`))return;if(!confirm('新PFCの主要データを救出JSONで上書きし、体型写真を追加します。実行しますか？'))return;go.disabled=bk.disabled=true;st.textContent='復元中…';try{const n=norm(d);for(const[k,v]of Object.entries(n))localStorage.setItem(F[k],v);if(n.dat){localStorage.removeItem('tf_deleted_today');localStorage.removeItem('tf_last_ai_added_ids')}const pc=await put(Array.isArray(d._pfcRescue?.bodyPhotos)?d._pfcRescue.bodyPhotos:[]);st.textContent=`復元完了: 主要データ ${Object.keys(n).length}項目 / 写真 ${pc}枚`;setTimeout(()=>{alert('復元が完了しました。新PFCを再読み込みします。');location.reload()},500)}catch(e){go.disabled=bk.disabled=false;st.textContent='復元エラー: '+(e?.message||e)}};
close.onclick=()=>{ov.remove();window.__PFC_RESTORE_RUNNING__=false};c.append(input,info,bk,go,close,st);ov.append(c);document.documentElement.append(ov);
})();